version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./www:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  composer:
    image: composer
    volumes:
      - ./www:/app
    command: install
